### ISSUE TITLE
Authorization failed: jwt must be a string

### ISSUE THREAD

**Issue by reyou** [wix/velo-external-db#529]
```
 velo-external-db:
    image: velo-external-db
    restart: always
    networks:
      - my_network
    environment:
      PORT: 8082
      CLOUD_VENDOR: azure
      TYPE: postgres
      HOST: host_postgres 
      DB: my_db
      USER: database_user
      PASSWORD: ***
      SECRET_KEY: secret_key
    ports:
      - "8082:8082"
```
	  
	  
I created image by generating from this repo.
Then I am running it in my VM (not cloud provider).

![image](https://github.com/wix/velo-external-db/assets/6571483/79272654-3240-4649-ad9f-1888e4ecd809)

But when I run following curl it says 

```
curl -L -X POST 'https://velo-external-db.mywebsite.net/schemas/list' \
-H 'Content-Type: application/json' \
--data-raw '{
    "requestContext": {
        "settings": {
            "secretKey": "myBigSecret"
        },
        "role": "OWNER"
    }
}'
```

`{"data":{"description":"Authorization failed: jwt must be a string"},"errorCode":"UNAUTHORIZED"}`

how can I fix this issue?
